<?php
include_once('C:\xampp\htdocs\ChooseNCruise\PHP\Controllers\AuthLib.php');
include_once('C:\xampp\htdocs\ChooseNCruise\PHP\Controllers\ConnectionFactory.php');
include_once('C:\xampp\htdocs\ChooseNCruise\PHP\Controllers\DBController.php');
include_once('C:\xampp\htdocs\ChooseNCruise\PHP\Controllers\SodiumManager.php');
include_once('C:\xampp\htdocs\ChooseNCruise\PHP\Controllers\TimestampManager.php');
include_once('C:\xampp\htdocs\ChooseNCruise\PHP\Controllers\TokenManager.php');
include_once('C:\xampp\htdocs\ChooseNCruise\PHP\Controllers\Validation.php');
?>
